version: "3.9"

services:
  musical_postgres:
    image: postgres:15-alpine
    restart: always
    container_name: musical_postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgresql_db:/var/lib/postgresql/data
  musical_web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: musical_web
    restart: always
    ports:
      - 8000:8000
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: >
      sh -c "python musicals/manage.py wait_for_db &&
              python musicals/manage.py migrate &&
              python musicals/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - musical_postgres

networks:
  default:

volumes:
  postgresql_db:
