# Generated by Django 5.1.3 on 2025-01-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_at', models.DateTimeField(null=True, verbose_name='오픈일시')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('thumbnail', models.URLField(null=True)),
                ('site', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='show.show')),
            ],
            options={
                'db_table': 'show_ticketopen',
                'constraints': [models.UniqueConstraint(fields=('name', 'site'), name='site_name_unique')],
            },
        ),
    ]
