# Generated by Django 5.1.3 on 2025-01-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_ticketopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketopen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketopen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
