# Generated by Django 5.1.3 on 2025-01-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_ticketopen_created_at_ticketopen_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketopen',
            name='has_detail_open_at',
            field=models.BooleanField(default=False),
        ),
    ]
